### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by jtr13** [jtr13/edav2#1]
- edit README
 - delete .Rmds not needed
 - add .Rmds new plots 
 - edit _bookdown.yml

**Comment by JasonSqz** [comment]
Hi Joyce,
We have added all the contents for all three chapters and ready for a takeoff. Could you go through all the contents and see if anything else should be added/ or need format change.  For readme, I am not sure what to put there and just put some titles.

**Comment by jtr13** [comment]
Sure will do. Thanks a lot!

**Comment by jtr13** [comment]
Closing this since these tasks are complete. I will comment on the chapters in the other issues.
