### ISSUE TITLE
Add chapter "Working with factors"

### ISSUE THREAD

**Issue by jtr13** [jtr13/edav2#11]
R resources part
based on "09CategoricalVariablesHowTo.html"
(forcats functions)

**Comment by jtr13** [comment]
Looks good... let's add the following:
example with `fct_inorder()` and example with `fct_infreq()`
Also fix typo 3.1 Recod to 3.1 Recode

**Comment by JasonSqz** [comment]
Corrected by Anni.
Resized some plots. Changed some x/y labels.
