### ISSUE TITLE
Add part info to first chapters of parts

### ISSUE THREAD

**Issue by jtr13** [jtr13/edav2#14]
Fix first chapter of R resources part

**Comment by jtr13** [comment]
I added the parts, but now I'm thinking that the ggplot2 chapter should go in the R graphics section. Any thoughts?

**Comment by anniechencan** [comment]
Hi Joyce, I just rewrote the learning_ggplot2 and put it into the R graphic section.

**Comment by jtr13** [comment]
Great! See you tomorrow.
