### ISSUE TITLE
Add hexbin to DESCRIPTION

### ISSUE THREAD

**Issue by jtr13** [jtr13/edav2#15]

**Comment by JasonSqz** [comment]
Added hexbin into DESCRIPTION, however, the graph still did not show up.

**Comment by jtr13** [comment]
It may be a caching issue. Can you try making small changes to the chunks with `geom_hex()` to break the cache?

**Comment by JasonSqz** [comment]
I made minor twist to the graph and cleared the cache of the browser. It is showing now!
