### ISSUE TITLE
Add chapter Faceting 

### ISSUE THREAD

**Issue by jtr13** [jtr13/edav2#17]
Add a short chapter after "Learning ggplot2" using material from 12ContinuousCategorical.pdf up to "Use `facet_grid` to add an additional variable" (but change that to "Use `facet_grid()` to facet on two variables" Skip everything else in that pdf.

**Comment by jtr13** [comment]
Is there something I should look at?

**Comment by JasonSqz** [comment]
Oh I am just adding to indicate who's working on which chapter. 
Actually Anni will be working on this one :)

**Comment by jtr13** [comment]
No prob, I'll unassign myself!
