### ISSUE TITLE
Add chapter Multidimensional Continuous

### ISSUE THREAD

**Issue by jtr13** [jtr13/edav2#18]
This chapter should have two sections: 
1. Parallel coordinate plots (13ParallelCoordinates.pdf -- skip everything before the first parallel coordinate plot slide.)
2. Biplots (14BiplotsCode.html -- skip everything before PCA)

**Comment by JasonSqz** [comment]
Chapter completed

**Comment by JasonSqz** [comment]
I am using library `redav` for the biplot section and GitHub action does not seem to recognize it. I put jtr13/redav in the remote section in DESCRIPTION, but it seems not to be the right way.

**Comment by jtr13** [comment]
It needs to be both in Remotes _and_ Imports (a fact that unfortunately I frequently forget...)

**Comment by JasonSqz** [comment]
Great! Fixed now.
