### ISSUE TITLE
Action Failed

### ISSUE THREAD

**Issue by JasonSqz** [jtr13/edav2#6]
Added three new libraries `datasets`,`ggridges`,`tidyverse` in DESCRIPTION.

**Comment by jtr13** [comment]
The problem we're running into is this one (or similar): https://github.com/r-lib/pak/issues/334 It seems that the problem occurs when there's a mistake in DESCRIPTION but then it persists even once it's been corrected. What I've been doing is restoring DESCRIPTION to a version that worked, and then slowing building it back. But to be clear, this shouldn't be necessary.
