### ISSUE TITLE
Consistency of capitalization in headings and subheadings

### ISSUE THREAD

**Issue by jtr13** [jtr13/edav2#9]
Let's use title case (only the first letter capitalized) for all headings and subheadings. So "Normal Distribution" should be "Normal distribution", etc.

**Comment by JasonSqz** [comment]
Fixed

**Comment by jtr13** [comment]
Thanks!

**Comment by JasonSqz** [comment]
Hi Joyce,
Checked through all the headings and fixed them. 
If you need help on modifying the last question in Pset2, I am available tonight.

P.s I just got the paycheck through mail for last two weeks.

**Comment by jtr13** [comment]
Great, thanks for letting me know!
